// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AoC = require("../AoC.bs.js");
var Tools = require("../Tools.bs.js");
var Pervasives = require("rescript/lib/js/pervasives.js");

AoC.getInput("2021", "7", (function (input_) {
        var input = input_.split(",").map(function (prim) {
              return parseInt(prim, 10);
            });
        var getFuel = function (align) {
          return Tools.reduce(input, 0, (function (acc, x) {
                        var diff = Pervasives.abs(align - x | 0);
                        return acc + (Math.imul(diff, diff + 1 | 0) / 2 | 0) | 0;
                      }));
        };
        var solve = function (_guess) {
          while(true) {
            var guess = _guess;
            var cur = getFuel(guess);
            if (getFuel(guess + 1 | 0) >= cur) {
              return cur;
            }
            _guess = guess + 1 | 0;
            continue ;
          };
        };
        console.log(solve(0));
        
      }));

/*  Not a pure module */
