// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AoC = require("../AoC.bs.js");
var Tools = require("../Tools.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

AoC.getInput("2020", "1", (function (input_) {
        var input = Tools.filterMap(Tools.lines(input_), Tools.string_to_int);
        var x = Tools.exn(Caml_option.undefined_to_opt(input.find(function (x) {
                      return input.includes(2020 - x | 0);
                    })));
        var __x = Math.imul(x, 2020 - x | 0);
        console.log("part 1:", __x);
        var __x$1 = Tools.exn(Tools.findMap(input, (function (x) {
                    return Tools.findMap(input, (function (y) {
                                  if (input.includes((2020 - x | 0) - y | 0)) {
                                    return Math.imul(Math.imul(x, y), (2020 - x | 0) - y | 0);
                                  }
                                  
                                }));
                  })));
        console.log("part 2:", __x$1);
        
      }));

/*  Not a pure module */
