// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AoC = require("../AoC.bs.js");
var Tools = require("../Tools.bs.js");
var Pervasives = require("rescript/lib/js/pervasives.js");

AoC.getInput("2020", "2", (function (input_) {
        var input = Tools.lines(input_).map(function (line) {
              var match = line.match(/([0-9]+)-([0-9]+)\s([a-z]):\s([a-z]+)/);
              if (match === null) {
                return Pervasives.failwith("Bad line: " + line);
              }
              if (match.length !== 5) {
                return Pervasives.failwith("Bad line: " + line);
              }
              var min = match[1];
              var max = match[2];
              var letter = match[3];
              var pass = match[4];
              return [
                      Tools.string_to_int(min),
                      Tools.string_to_int(max),
                      letter,
                      pass
                    ];
            });
        var __x = Tools.count(input, (function (param) {
                var letter = param[2];
                var l = Tools.count(param[3].split(""), (function (x) {
                        return x === letter;
                      }));
                if (l >= param[0]) {
                  return l <= param[1];
                } else {
                  return false;
                }
              }));
        console.log("part 1:", __x);
        var __x$1 = Tools.count(input, (function (param) {
                var pass = param[3];
                var letter = param[2];
                return pass[param[0] - 1 | 0] === letter !== (pass[param[1] - 1 | 0] === letter);
              }));
        console.log("part 2:", __x$1);
        
      }));

/*  Not a pure module */
