// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AoC = require("../AoC.bs.js");
var Tools = require("../Tools.bs.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

AoC.getInput("2020", "6", (function (input_) {
        var input = input_.split("\n\n").map(Tools.lines);
        var __x = Tools.mapSum(input, (function (lines) {
                return Belt_SetString.size(Belt_SetString.fromArray(lines.join("").split("")));
              }));
        console.log("part 1:", __x);
        var __x$1 = Tools.mapSum(input, (function (lines) {
                return Tools.count(lines[0].split(""), (function (x) {
                              return lines.every(function (__x) {
                                          return __x.includes(x);
                                        });
                            }));
              }));
        console.log("part 2:", __x$1);
        
      }));

var $$Set;

exports.$$Set = $$Set;
/*  Not a pure module */
