// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(set) {
  return set;
}

function has(set, value) {
  return set.charAt(value) === "#";
}

function replaceAt(str, index, value) {
  return str.substring(0, index) + value + str.substring(index + 1 | 0);
}

function add(set, value) {
  if (has(set, value)) {
    return set;
  }
  var x = value - set.length | 0;
  if (x >= 0) {
    return set + ".".repeat(x) + "#";
  } else {
    return replaceAt(set, value, "#");
  }
}

function remove(set, value) {
  if (has(set, value)) {
    return replaceAt(set, value, ".");
  } else {
    return set;
  }
}

function toArray(set) {
  var result = [];
  for(var i = 0 ,i_finish = set.length; i < i_finish; ++i){
    if (has(set, i)) {
      result.push(i);
    }
    
  }
  return result;
}

function size(set) {
  return toArray(set).length;
}

var empty = "";

exports.empty = empty;
exports.toString = toString;
exports.has = has;
exports.add = add;
exports.remove = remove;
exports.toArray = toArray;
exports.size = size;
/* No side effect */
